<?php

namespace Mobility\PlacementBundle\Entity;

use Doctrine\ORM\EntityRepository;

/**
 * PlacementRepository
 *
 * This class was generated by the Doctrine ORM. Add your own custom
 * repository methods below.
 */
class PlacementRepository extends EntityRepository
{
	public function getPlacements($year) {
		$qb = $this->createQueryBuilder('p')
			->leftJoin('p.student', 's')
			->addSelect('s')
			->where('p.year = :year')
			->setParameter('year', $year)
			->orderBy('s.surname', 'asc');

		return $qb->getQuery()->getResult();
	}

	public function getYears() {
		$qb = $this->createQueryBuilder('p')
			->select('p.year')
			->groupBy('p.year')
			->orderBy('p.year', 'desc');

		$values = $qb->getQuery()->getScalarResult();
		$r = array();
		foreach ($values as $v) {
			$r[] = $v['year'];
		}

		return $r;
	}
}
