<?php

namespace Mobility\UniversityBundle\Entity;

use Doctrine\ORM\EntityRepository;

/**
 * UniversityRepository
 *
 * This class was generated by the Doctrine ORM. Add your own custom
 * repository methods below.
 */
class UniversityRepository extends EntityRepository {
    public function getActiveUniversitiesQueryBuilder() {
        $qb = $this->createQueryBuilder('u')
                ->where('u.partnershipState = :active')
                ->setParameter('active', true)
                ->orderBy('u.name', 'asc');
        
        return $qb;
    }

    public function getAllUniversitiesQueryBuilder() {
        $qb = $this->createQueryBuilder('u')
                ->orderBy('u.name', 'asc');
        
        return $qb;
    }
}
