<?php

namespace Mobility\StudentBundle\Entity;

use Doctrine\ORM\EntityRepository;

/**
 * WishRepository
 *
 * This class was generated by the Doctrine ORM. Add your own custom
 * repository methods below.
 */
class WishRepository extends EntityRepository {
    public function count() {
        $qb = $this->createQueryBuilder('w')
                ->select('count(w)');
        
        return $qb->getQuery()->getSingleScalarResult();
    }

    public function maxChoices() {
        $qb = $this->createQueryBuilder('w')
                ->select('count(w)')
                ->groupBy('w.student');

		$res = $qb->getQuery()->getScalarResult();
		$max = 0;
		foreach ($res as $count) {
			if ($count > $max) $max = $count;
		}
		print_r($max);

		return $max;
    }
}
