<?php

namespace Mobility\MainBundle\Entity;

use Doctrine\ORM\EntityRepository;

/**
 * YearRepository
 *
 * This class was generated by the Doctrine ORM. Add your own custom
 * repository methods below.
 */
class YearRepository extends EntityRepository
{
	public function getYears() {
		$qb = $this->createQueryBuilder('y')
			->select('y.year')
			->orderBy('y.year', 'desc');

		$values = $qb->getQuery()->getScalarResult();
		$r = array();
		foreach ($values as $v) {
			$r[] = $v['year'];
		}

		return $r;
	}
}
